name: Shopper
description: Shopping list app.
publish_to: 'none'
version: 1.3.0

environment:
  sdk: '>=2.19.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  http: ^0.13.5
  provider: ^6.0.5
  flutter_map_marker_popup: ^4.0.1
  collection: ^1.17.0
  url_launcher: ^6.1.10
  phone_number: ^1.0.0
  drag_and_drop_lists: ^0.3.3
  flutter_map_location_marker: ^5.2.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  hive_generator: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
flutter:
  uses-material-design: true
  assets:
    - assets/pinGreen.png
    - "assets/empty.png"
    - assets/recipes.json